### ISSUE TITLE
Antoine ROY feedback 26/11/2024

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor-video#4]
### Ouverture du plugin annotation > Click sur Note >
 
- [x]  Le canvas ( grand cadre bleu) est mal positionné par rapport à la vidéo: 

![image](https://github.com/user-attachments/assets/9e50dc96-4ea1-4329-926c-35263ac09f29)

- [x] Impossible de cibler une zone du canvas pour placer ma note 

- [x] Lorsqu'on appuis sur la flèche pour incrémenter en négatif le timer de l'annotation alors que celui ci est à 0, il est possible de set des heures au format '5-' sur une vidéo qui ne fait que 12 secondes (cf screen ci-après)
![image](https://github.com/user-attachments/assets/bc64e49b-e660-4234-8408-f8edbb4c3c7e)

- [x]  au hover sur la video un cadre violet apparaît
- [x] En dessous des boutons cancel / save il y a un texte "video" positionné 

###    Ouverture du plugin annotation > Click sur Tag >

- [x] même remarque qu'a la section du dessus 

###    Ouverture du plugin annotation > Click sur Image >
- [x] même remarque qu'a la section du dessus 

- [x] Lorsqu'on upload une image celle ci apparaît sur la partie bleue  et lorsqu’on essaye de la déplacer sur la vidéo l'image passe dessous.
- [x] Quand on essaye de save une annotation avec image rien ne se passe et j'ai une erreur 'canvas is unedifined' (cf screen ci-après) 
![image](https://github.com/user-attachments/assets/15fd3dad-76f2-4cca-b4dc-c100eb591039)
 
###    Ouverture du plugin annotation > Click sur Image > Overlay 

- [x] même remarque qu'a la section du dessus (Image) 
- [x] Impossible de dessiner en 'free hand' 
- [x] Il est possible de créer plusieurs texte overlay lié au même imput texte (cf screen ci-après) : 
![image](https://github.com/user-attachments/assets/106f0948-8fba-4220-a3a3-115a51a636d7)

### General

- Il n'y aucun tooltip

**Comment by geourjoa** [comment]
Thanks for the feedback

**Comment by geourjoa** [comment]
- [ ] On Image template, drawingState is not reload correctly. I pushed a bit early 

To fix, use something like this : 

ImageCommentTemplate L102

```js

 const initDrawingState = () => {
    if (annotationState.maeData.target.drawingState) {
      return {
        ...JSON.parse(annotationState.maeData.target.drawingState),
        isDrawing: false,
      };
    }
    
    ```
