### ISSUE TITLE
Video manifest with peertube link doesn't load

### ISSUE THREAD

**Issue by Drilio** [SCENE-CE/mirador-annotation-editor-video#5]
when you create a peertube video manifest like :
```
{"@context":"https://iiif.io/api/presentation/3/context.json","id":"./upload/86f0960e53c9e849702812126ec3b5c72cec7814/test peertube vidéo.json","type":"Manifest","label":{"en":["test peertube vidéo"]},"items":[{"id":"https://example.org/1734361638516/canvas/1734361638516","type":"Canvas","height":1080,"width":1920,"duration":914,"label":{"en":["Image Item"]},"items":[{"id":"https://example.org/1734361638516/canvas/1734361638516/annotation-page/1734361638516","type":"AnnotationPage","items":[{"id":"https://example.org/1734361638516/annotation/1734361638518","type":"Annotation","motivation":"painting","target":"https://example.org/1734361638516/canvas/1734361638516","body":{"id":"https://peertube.fr/w/48uz581ZbdNvWyXC9KV37n","type":"Video","format":"Video/MPG","height":1080,"width":1920,"duration":914}}]}]}],"thumbnail":{"@id":"","service":{"@context":"","@id":"","profile":""}}}
```

and load it into mirador with video it results into this comportement :  

![image](https://github.com/user-attachments/assets/51ccc2ad-b5b1-4d76-91d8-4903868971e2)
the manifest never loads.

**Comment by daxid** [comment]
@Drilio mets le fichier du manifest en PJ STP

**Comment by geourjoa** [comment]
Can you expose this manifest on the web ?

And have you tested it in MV alone  ?

**Comment by Drilio** [comment]
[test peertube vidéo.json](https://github.com/user-attachments/files/18152764/test.peertube.video.json)

**Comment by Drilio** [comment]
When I try to open it in MV : 
![image](https://github.com/user-attachments/assets/eba902b2-c9c0-4ba8-a808-d2125dc1dee8)

**Comment by geourjoa** [comment]
@Drilio 

This problem seem to be related to peertube.fr

If it's working here it's suffisent 

arverst-peertube.tetras-libre.fr
